Download router config
ibi-group/datatools-server pull request #294
Opened 2020-04-01 21:40 UTC by landonreed

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

- fix #293 (handle router-config upload/download for instances downloading Graph.obj)
- fix #292 (check that instances properly added to target group)

2020-04-01 22:09 UTC, evansiroky commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +    }
Lots of common code here. Seems like another method could be created with just the ObejctMapper writing stuff to bytes part.

2020-04-01 22:09 UTC, evansiroky requested changes
Just one thing.

2020-04-06 19:52 UTC, evansiroky commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +        mapper.setSerializationInclusion(Include.NON_NULL);
ObjectMapper no longer needed here. Please remove.

2020-04-06 19:53 UTC, evansiroky approved these changes
Good to go after removing some dead code.

2020-04-06 20:33 UTC, binh-dam-ibigroup approved these changes
One small suggestion, good to do.

2020-04-06 21:52 UTC, landonreed commented on src/main/java/com/conveyal/datatools/manager/jobs/MonitorServerStatusJob.java
>          LOG.info(message);
Nah, you can't tell in this limited preview, but the same message is used below, so it needs to be formatted with String#format.

2020-04-09 16:41 UTC, merged

2020-07-06 18:37 UTC, landonreed commented
:tada: This PR is included in version 3.7.0 :tada:

The release is available on [GitHub release](https://github.com/ibi-group/datatools-server/releases/tag/v3.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: