GTFS spec updates
ibi-group/datatools-server pull request #387
Opened 2021-06-04 10:41 UTC by br648

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR seeks to integrate the latest GTFS spec updates made under the GTFS-lib PR (https://github.com/conveyal/gtfs-lib/pull/312) in particular the two new table types: attributions and translations. This PR must not be merged until the depended GTFS-lib PR (https://github.com/conveyal/gtfs-lib/pull/312) has been merged and release created.

2021-06-07 14:52 UTC, binh-dam-ibigroup approved these changes
LGTM with minor formatting comments.

2021-06-07 14:52 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/datatools/editor/controllers/api/EditorControllerTest.java
> +        String table) throws IOException {
Place `) throws ...` on a new line.

2021-06-07 14:52 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/datatools/editor/controllers/api/EditorControllerTest.java
> +        canPatchTable(field, entity, expectedCount, graphQLQueryFile, table);
Non-blocking: It looks like `canPatchTable` is only used once, so it could be inlined.

2021-06-07 19:48 UTC, evansiroky commented on src/test/resources/graphql/attributions.txt
> +query ($namespace: String) {
Seeing this GraphQL reminded me that we should probably add snapshot tests to the GraphQL schema in gtfs-lib for these things.

2021-06-07 20:02 UTC, evansiroky requested changes
Let's fix the failing tests. Perhaps it'd be good to develop a set of fake feeds with the minimum required data elements needed to simulate various merging possibilities.

2021-06-17 16:28 UTC, evansiroky approved these changes

2021-07-20 14:55 UTC, binh-dam-ibigroup requested changes
New fields introduced (e.g. `continuous_pickup`) should be available when exporting a GTFS archive after setting values on these fields in the editor.

2021-09-02 13:28 UTC, binh-dam-ibigroup approved these changes

2021-09-02 13:50 UTC, merged