Remove VERSION_CLONE transform
ibi-group/datatools-server pull request #404
Opened 2021-07-20 16:16 UTC by landonreed

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

Companion PR to https://github.com/ibi-group/datatools-ui/pull/692 that removes the clone operation during ProcessSingleFeedJob. During the original development of this transform feature, it was thought that there may be a need to preserve the original copy of the GTFS file that was transformed, but in practice we have determined that this goes unused.

2021-07-20 16:28 UTC, miles-grant-ibigroup requested changes
It looks like the tests may still be expecting the old behavior?

2021-07-21 16:06 UTC, landonreed commented
@miles-grant-ibigroup, since the functionality tested by the failing test was removed, I went ahead and removed that test.

2021-07-21 17:44 UTC, miles-grant-ibigroup approved these changes

2021-07-21 18:58 UTC, binh-dam-ibigroup approved these changes

2021-07-21 21:55 UTC, evansiroky approved these changes

2021-07-21 21:56 UTC, merged