Reduce feedsource mongo queries
ibi-group/datatools-server pull request #498
Opened 2022-12-05 21:01 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing
- [x] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [x] e2e tests are all passing _(remove this if not merging to master)_

### Description

Reduces `FeedSource` endpoint loading time by removing expensive mongo queries and instead saving data into static fields. Does use old method if those static fields are missing.

2022-12-06 08:06 UTC, br648 commented
The test `canRetrieveFeedSourceWithDeployedFeedVersion` no longer works locally for me because the following is missing from the params `deployedFeedVersionStartDate` and `deployedFeedVersionEndDate`:

`@JsonSerialize(using = JacksonSerializers.LocalDateIsoSerializer.class)`
`@JsonDeserialize(using = JacksonSerializers.LocalDateIsoDeserializer.class)`

2022-12-06 09:06 UTC, br648 requested changes

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/jobs/DeployJob.java
> +        FeedVersion deployedFeedVersion = Persistence.feedVersions.getById(deployment.feedVersionIds.stream().findFirst().get());
I'm not sure I'd trust this. Perhaps more testing is required e.g. a deployment with more than one feed version. It might be safer to retrieve all feed versions from the DB and select the newest?

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +
Remove these two empty lines.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +    public String deployedFeedVersionId = "🤌";
This would be better as an empty string or null.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +        if (this.latestFeedVersion == null) {
All uses of `this.` can be removed from this method.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +    public void setDeploymentInfo(String versionId, LocalDate startDate, LocalDate endDate) {
All uses of `this.` can be removed from this method.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +        if (this.deployedFeedVersionId == null) {
All uses of `this.` can be removed from this method.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +            return this.getDeployedFeedVersionViaExpensiveQuery().id;
Need to check and handle a null being returned from this method.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +        if (this.deployedFeedVersionStartDate == null) {
All uses of 'this'. can be removed from this method.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +        if (this.deployedFeedVersionStartDate == null) {
All uses of `this.` can be removed from this method.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +                    eq("projectId", this.projectId),
Revert indentation.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +                        .filter(feedVersion -> deployment.feedVersionIds.contains(feedVersion.id))
Revert indentation.

2022-12-06 09:06 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedSource.java
> +
Remove these two empty lines.

2022-12-06 13:43 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/DeployJob.java
> +        FeedVersion deployedFeedVersion = Persistence.feedVersions.getById(deployment.feedVersionIds.stream().findFirst().get());
The problem with that is the number of internal mongo queries this fires off. The solution might be to sort `deployment.feedVersionIds` but I'm not sure how

2022-12-06 14:33 UTC, miles-grant-ibigroup commented
@br648 changes are addressed and unit tests are repaired

2022-12-06 16:11 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/jobs/DeployJob.java
> +        FeedVersion deployedFeedVersion = Persistence.feedVersions.getById(deployment.feedVersionIds.stream().findFirst().get());
Sorting isn't going to help as the feed version ids are just that, ids. We need the latest date which of course will result in a db query on the provided feed version ids.

A null pointer check needs to be added in case `deployedFeedVersion` is null for some reason.

2022-12-07 13:59 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/DeployJob.java
> +        FeedVersion deployedFeedVersion = Persistence.feedVersions.getById(deployment.feedVersionIds.stream().findFirst().get());
Null check added in 2d787feb8afdd4d524d12c7e46d6beaff8d53992

2022-12-07 16:44 UTC, br648 approved these changes
LGTM. Glad that FIXME has gone!

2022-12-09 22:03 UTC, philip-cline approved these changes
Nice! Glad we could get this looking good

2022-12-09 22:03 UTC, merged