Add MobilityData GTFS Validator to validation step
ibi-group/datatools-server pull request #512
Opened 2023-02-16 15:08 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR integrates the [MobilityData GTFS Validator](https://github.com/MobilityData/gtfs-validator) into datatools, and adds a MobilityData validation to the GTFS validation step. Validation results are saved to a unique temporary folder, then loaded and inserted into Mongo. Failures are handled via the existing validation failure infrastructure.

#### Room for Improvement
- [ ] I'd like to perhaps see the MobilityData validation happen in a second thread, possibly in parallel to the existing validation. However, I'm not sure how to do this in the cleanest way, and the new validation isn't that slow, especially compared to the existing one.

#### Important Notices
The MobilityData validator requires a much newer version of the Java spec. I've updated by JDK to 18, and language level to 11!

2023-02-17 16:39 UTC, br648 commented
@miles-grant-ibigroup for review: https://github.com/ibi-group/datatools-server/pull/513. We should discuss at some point next week.

2023-02-20 10:40 UTC, br648 commented
@miles-grant-ibigroup I'm going to defer my review until this https://github.com/ibi-group/datatools-server/pull/513 is tested and merged.

2023-03-06 16:48 UTC, br648 requested changes

2023-03-06 16:48 UTC, br648 commented on pom.xml
> +                        --illegal-access=permit
Consider adding a comment to explain this.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/transform/NormalizeFieldTransformation.java
> +                    // Modify target zip file that we just read.
Nit. Restore original indentation.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            status.update("MobilityData Analysis...", 11);
11% complete, is this just an arbitrary value!

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +        FileReader fr = null;
Remove redundant null assignment.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            fr = new FileReader(validatorOutputDirectory + "report.json");
Change to try with resources:

`String json;`
`try (FileReader fr = new FileReader(validatorOutputDirectory + "report.json")) {`
`    BufferedReader in = new BufferedReader(fr);`
`    json = in.lines().collect(Collectors.joining(System.lineSeparator()));`
`}`

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +        FileReader fr = null;
Remove completely. See try with resources comment below.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            // Namespace based folders avoid clash for validation being run on multiple versions of a feed
Nit. Full stop.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            // Set up MobilityData validator
Nit. Full stop.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            // Run MobilityData validator
Nit. Full stop.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            // This will persist the document to Mongo
Nit. Full stop.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +            // Read generated report and save to Mongo
Nit. Full stop.

2023-03-06 16:48 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +        // VALIDATE GTFS feed
Nit. Full stop.

2023-03-08 18:16 UTC, miles-grant-ibigroup commented
Thanks Rob! All changes have been addressed

2023-03-09 07:48 UTC, br648 approved these changes
All good. Good luck presenting the new data!

2023-03-09 20:51 UTC, philip-cline approved these changes
Looking good to me, seems to work well.

2023-03-09 20:51 UTC, philip-cline commented on src/main/java/com/conveyal/datatools/manager/models/FeedVersion.java
> +        // VALIDATE GTFS feed.
Amazing

2023-03-10 13:31 UTC, merged