adjust OtpRouterConfig to be otp2-compatible
ibi-group/datatools-server pull request #533
Opened 2023-05-01 20:36 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing
- [x] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [x] e2e tests are all passing _(remove this if not merging to master)_

### Description

This is the backend portion of a 2 portion PR to make the GUI-based router config editor OTP2 compatible.

Needs https://github.com/ibi-group/datatools-ui/pull/946

2023-05-02 16:29 UTC, philip-cline requested changes
Just a quick questions about the included fields

2023-05-02 16:29 UTC, philip-cline commented on src/main/java/com/conveyal/datatools/manager/models/OtpRouterConfig.java
> +        public String feedId;
Do you need to add other fields above `Updater` for the other fields introduced in https://github.com/ibi-group/datatools-ui/pull/946/files?, e.g. `driveDistanceReluctance`, `nonTransitGeneralizedCostLimit`, etc.

2023-05-03 11:46 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/OtpRouterConfig.java
> +        public String feedId;
You'd think but somehow the values are saving?

2023-05-03 11:59 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/OtpRouterConfig.java
> +        public String feedId;
Good catch thanks this is fixed in 128a180fa687026356952a5a5bfbab50892f86b2

2023-05-10 19:36 UTC, philip-cline approved these changes

2023-05-11 13:08 UTC, br648 approved these changes
A few minor items, apart from them, all good.

2023-05-11 13:08 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +                ? customRouterConfig.getBytes(StandardCharsets.UTF_8) : null;
Nit. Line the colon up with the question mark.

2023-05-11 13:08 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +            Map<String, Object> merged = new HashMap<String, Object>(map2);
I don't think the `merged` HashMap is required here. Can you not just do `map2.putAll(map1);`? Could also do some inlining with map1, but this reads better.

2023-05-11 13:08 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +                LOG.error("Failed to generate router config:");
Combine these two lines to: `LOG.error("Failed to generate router config: ", e);`

2023-05-11 13:08 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +                return new String(this.generateRouterConfig(), "UTF-8");
`this.` is not needed. Replace `"UTF-8"` with `StandardCharsets.UTF_8`

2023-05-12 14:16 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/Deployment.java
> +            Map<String, Object> merged = new HashMap<String, Object>(map2);
Yeah I tried to stay verbose since this method is a bit confusing. I think the reason for the extra map is because the `putAll` returns `void`

2023-05-12 14:16 UTC, miles-grant-ibigroup commented
Thanks for the feedback! Good suggestions

2023-05-12 14:27 UTC, merged