Flex transformation updates
ibi-group/datatools-server pull request #550
Opened 2023-07-20 11:08 UTC by br648

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Update to accommodate flex tables in transformations.

2023-08-30 15:02 UTC, philip-cline requested changes
Super clean fix, this is looking awesome! Thanks for setting this up. Just a couple of comments

2023-08-30 15:02 UTC, philip-cline commented on src/main/java/com/conveyal/datatools/manager/jobs/ProcessSingleFeedJob.java
> +                    feedVersion.validationResult.lastCalendarDate
Reuse variable?
```suggestion
                    validationResult.firstCalendarDate,
                    validationResult.lastCalendarDate
```

2023-08-30 15:02 UTC, philip-cline commented on src/main/java/com/conveyal/datatools/manager/jobs/ProcessSingleFeedJob.java
> +            if (validationResult != null) {
Can we nest this condition under the `validationResult != null` check above?

2023-09-27 19:33 UTC, philip-cline approved these changes

2023-09-28 15:17 UTC, binh-dam-ibigroup approved these changes
Nice cleanup, see the few nice-to-have tweaks. repo.opengeo.org is not responsive at the moment, and I am not able to download dependencies, but I'm going to approve anyway.

2023-09-28 15:17 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/ProcessSingleFeedJob.java
> +            if (validationResult != null) {
Phil's comment above was not addressed.

2023-09-28 15:17 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/transform/NormalizeFieldTransformation.java
>          String tableName = table + ".txt";
Use `getTableName` defined in `FeedTransformation`.

2023-09-28 15:17 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/datatools/manager/jobs/ProcessSingleFeedJobNotificationTest.java
> -        String expectedResult = String.format("New feed version created for Mock Feed Source (valid from %s - %s). During validation, we found 100 issue(s)",
Revert this change (tweak the underlying code to that space is restored).

2023-09-28 15:17 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/datatools/manager/jobs/ProcessSingleFeedJobNotificationTest.java
> -        String expectedResult = String.format("New feed version created for Mock Feed Source (valid from %s - %s). The validation check found no issues with this new dataset!",
Revert this change (tweak the underlying code to that space is restored).

2023-09-28 15:17 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/datatools/manager/jobs/NormalizeFieldTransformJobTest.java
> +        initializeFeedSource(TABLE_NAME, transformation);
Would it make sense to inline `TABLE_NAME` or `FIELD_NAME`, or move their declarations to this method?

2023-10-25 12:37 UTC, merged