Fold MTC deploy back to dev
ibi-group/datatools-server pull request #589
Opened 2024-03-04 18:46 UTC by binh-dam-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR brings changes specific to MTC branch back to dev.

2025-05-22 15:13 UTC, miles-grant-ibigroup requested changes
Looks ok in testing but I just have a few things I want to double check!

2025-05-22 15:13 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/FeedUpdater.java
> +                .allowDiskUse(true)
What was going on here? I worry this might cause a slowdown

2025-05-22 15:13 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/transform/NormalizeFieldTransformation.java
> +        // If the index is -1, this is a new column, and we need to add it accordingly.
Just confirming that all this refactoring is only to add support for adding a new column via the normalize transformation? I have slight worries about how this is going to interact with flex (where I think we solved this problem in a different way) but I guess that's a problem for later

2025-05-22 15:21 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/transform/NormalizeFieldTransformation.java
> +        // If the index is -1, this is a new column, and we need to add it accordingly.
The `NormalizeFieldTransformation` logic in the dev branch already adds a new column if a field is unknown, See previous line 201 in the diff. We changed that for MTC in #617.

2025-05-22 15:32 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/FeedUpdater.java
> +                .allowDiskUse(true)
This was from #570. If https://github.com/ibi-group/datatools-server/pull/570#pullrequestreview-1680034980 is still important, we can file a PR on mtc-deploy to restrict that to the MTC extension.

2025-05-23 15:11 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/FeedUpdater.java
> +                .allowDiskUse(true)
@miles-grant-ibigroup We might be able to just remove this line altogether, as disk use is enabled by default now: https://www.mongodb.com/docs/manual/reference/method/cursor.allowDiskUse/#mongodb-method-cursor.allowDiskUse

2025-05-23 18:15 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/FeedUpdater.java
> +                .allowDiskUse(true)
Love it!

2025-05-23 18:15 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/FeedUpdater.java
> +                .allowDiskUse(true)
Once we get that line removed in mtc-deploy I'm happy to approve

2025-05-23 18:15 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/transform/NormalizeFieldTransformation.java
> +        // If the index is -1, this is a new column, and we need to add it accordingly.
Thank you for the clarification!

2025-05-27 13:23 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/jobs/FeedUpdater.java
> +                .allowDiskUse(true)
@miles-grant-ibigroup  See #624.

2025-05-27 17:11 UTC, miles-grant-ibigroup approved these changes
Approved with #624 merged

2025-06-05 09:29 UTC, br648 approved these changes
Some minor comments but apart from these this is good.

2025-06-05 09:29 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/gtfsplus/DirectionsScanner.java
> +        // Find the route_id and realtime_enabled index from the headers.
Either this comment is wrong or realtime_enabled is needed?

2025-06-05 09:29 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/gtfsplus/GtfsPlusValidation.java
> +
Remove empty line.

2025-06-05 09:29 UTC, br648 commented on src/main/java/com/conveyal/datatools/manager/models/transform/ReplaceFileFromStringTransformation.java
> +        try(FileSystem targetZipFs = FileSystems.newFileSystem(targetZipPath, (ClassLoader) null)) {
Space after `try`.

2025-06-09 14:53 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/models/transform/ReplaceFileFromStringTransformation.java
> +        try(FileSystem targetZipFs = FileSystems.newFileSystem(targetZipPath, (ClassLoader) null)) {
Fixed in https://github.com/ibi-group/datatools-server/pull/589/commits/ee203531500e572fcb51496610a90f34ddd5e48e

2025-06-09 14:54 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/gtfsplus/GtfsPlusValidation.java
> +
Fixed in https://github.com/ibi-group/datatools-server/pull/589/commits/adf598cf9f578ed5c2c1ea999721b737e105921e.

2025-06-09 14:55 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/datatools/manager/gtfsplus/DirectionsScanner.java
> +        // Find the route_id and realtime_enabled index from the headers.
@br648 The comment was a result of copy-paste from `RealtimeRoutesScanner`, I updated it in https://github.com/ibi-group/datatools-server/pull/589/commits/734193752f92e5e49295fc3c925fd6f244094339.

2025-06-09 19:05 UTC, binh-dam-ibigroup commented
@br648 and @miles-grant-ibigroup GH says your reviews are stale, so I'm requesting you do that, please.

2025-06-10 07:26 UTC, br648 approved these changes
All good. Looks like it was just the validate stop code prefix PR being merged.

2025-06-10 07:43 UTC, br648 commented
@binh-dam-ibigroup 

The PR "MTC: Validate stop code prefixes" which has been merged into this PR requires the following GTFS-Lib PR:

https://github.com/ibi-group/gtfs-lib/pull/14

Jym is still to review and I have reminded him of this. Just so you are aware!

2025-06-13 20:38 UTC, miles-grant-ibigroup approved these changes
Everything is merged, I'm good to go!

2025-06-16 15:18 UTC, merged